### ISSUE TITLE
Caching doesn't seem to work

### ISSUE THREAD

**Issue by lovasoa** [mymindstorm/setup-emsdk#1]
Reading the code, it looks like this action tries to cache emscripten.
However, when testing this action it seems that emscripten is downloaded every time the action is run.
This also seems to happen on this project's own CI: https://github.com/mymindstorm/setup-emsdk/commit/719809ab3ca63fc6524b99a1b397fffb3a56cec9/checks?check_suite_id=199572675

**Comment by mymindstorm** [comment]
It tries to cache, but I didn't have the time (after fighting with it for a while) to figure out why it refused to cache the downloaded release. If you're willing to take a shot at it I'd be happy to merge any fixes, otherwise I'll see when I can get around to looking into it again.

**Comment by lovasoa** [comment]
The code also looks fine to me. Maybe caching doesn't work exactly the way the docs say it does

**Comment by mymindstorm** [comment]
Yep, that's it. https://github.com/actions/toolkit/issues/58#issuecomment-521672239

**Comment by mymindstorm** [comment]
@lovasoa [This](https://github.com/actions/toolkit/issues/47#issuecomment-548416562) was released recently. It doesn't seem to integrate into their actions API. 

I saw you made your own version of this. If you still plan to use this I'll throw together a `use-directory` option that will add to path based on a user supplied directory.

**Comment by lovasoa** [comment]
It would be great to be able to use https://github.com/actions/cache, yes !

**Comment by Skycoder42** [comment]
I personally think, that having two different steps for cached or not cached is not very elegant... How about using just one input for both, an instead pass the cache hit boolean as additional input?
