### ISSUE TITLE
Unable to process command ::add-path

### ISSUE THREAD

**Issue by lovasoa** [mymindstorm/setup-emsdk#10]
Recently, this action started failing with the following error : 

The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/

**Comment by mymindstorm** [comment]
Are you using version 7? It should be on a version of @actions/core that has already fixed this

**Comment by lovasoa** [comment]
I was indeed using an old version. Sorry for the inconvenience !
