### ISSUE TITLE
Option to avoid running `construct_env`?

### ISSUE THREAD

**Issue by bakkot** [mymindstorm/setup-emsdk#26]
[emsdk construct_env](https://github.com/mymindstorm/setup-emsdk/blob/f8b10cde48668a05d65c7d1ad56a038f57756719/src/main.ts#L95) [will clobber the PATH for other tools like node](https://github.com/emscripten-core/emsdk/issues/1142), which can be annoying if you need a later version of node. It would be nice if this could be avoided (possibly with an opt-in option, to avoid breaking changes).

Per [this comment](https://github.com/emscripten-core/emsdk/issues/1142), you can instead set the `EM_CONFIG` environment variable to make `emcc` work without clobbering any other tools. That seems better. It also [seems like](https://github.com/emscripten-core/emsdk/issues/1142) it should be the default, but unless emsdk adopts that behavior, this would be helpful.

**Comment by mymindstorm** [comment]
It looks like this was fixed upstream, so I am going to close this issue for now. https://github.com/emscripten-core/emsdk/pull/1189
