### ISSUE TITLE
Error when run on ubuntu

### ISSUE THREAD

**Issue by connorjclark** [mymindstorm/setup-emsdk#30]
It seems like it's downloading the mac version of the binaries somehow.

https://github.com/connorjclark/ZeldaClassic/actions/runs/3717330481/jobs/6304571033#step:9:11

https://github.com/emscripten-core/emscripten/issues/8622#issuecomment-493113693

When run on macos jobs it works fine tho

**Comment by connorjclark** [comment]
Oh, since I was going from mac->ubuntu and was providing a cache key, I accidentally got the cached version of mac for the linux job.

https://github.com/mymindstorm/setup-emsdk/blob/master/src/main.ts#L30

Maybe the os should be appended to the cache key to prevent this footgun?

**Comment by mymindstorm** [comment]
@connorjclark thanks for this, I've pushed a release to implement your suggestion via ab889da2abbcbb280f91ec4c215d3bb4f3a8f775.
