### ISSUE TITLE
How to sponsor/donate? 

### ISSUE THREAD

**Issue by strager** [mymindstorm/setup-emsdk#36]
My project uses setup-emsdk and I would like to tip the developers. Do you permit GitHub Sponsors or any other way to contribute financially?

**Comment by mymindstorm** [comment]
I appreciate that you are willing to sponsor open-source developers! Currently, I cannot accept financial contributions for my open-source projects. I feel this way because I don't have enough time to dedicate to maintenance between full-time college and a part-time job.
