### ISSUE TITLE
node12 -> node16

### ISSUE THREAD

**Issue by vadimkantorov** [mymindstorm/setup-emsdk#39]
Started having a warning by GitHub actions:
<hr>
The following actions uses node12 which is deprecated and will be forced to run on node16: mymindstorm/setup-emsdk@v11. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/

**Comment by mymindstorm** [comment]
I have updated the action to use Node 20, please let me know if you run into any issues.

**Comment by vadimkantorov** [comment]
Also please update `v11` to `v13` in the README example

**Comment by mymindstorm** [comment]
oops, forgot to push that commit
