### ISSUE TITLE
"Tip of tree" (tot) version doesn't work

### ISSUE THREAD

**Issue by lovasoa** [mymindstorm/setup-emsdk#4]
When one wants to try the latest unpublished version of emscripten, emsdk lets you do : 

```
emsdk install tot
```

But using `tot` as the version in this action leads to : 

```
Tip-of-tree information was not found, run emsdk update-tags
```

**Comment by lovasoa** [comment]
Cool, thanks for implementing this 👍

**Comment by mymindstorm** [comment]
Np, it's published as v4

**Comment by lovasoa** [comment]
Thank you ! I've used it in sql.js
